// "code",
// "loan_product_code",
// "loan_product_name",
// "loan_bank",
// "gps_fee",
// "auth_fee",
// "fee",
// "month_rate",
// "credit_code",
// "biz_type",
// "loan_period",
// "invoice_company",
// "car_brand",
// "original_price",
// "invoice_price",
// "car_color",
// "month_deposit",
// "first_amount",
// "first_rate",
// "loan_amount",
// "settle_address",
// "apply_user_name",
// "gender",
// "marry_state",
// "nation",
// "education",
// "id_no",
// "family_number",
// "mobile",
// "now_address",
// "post_code1",
// "residence_address",
// "post_code2",
// "family_main_asset",
// "main_asset_include",
// "main_income",
// "work_company_name",
// "work_company_address",
// "self_company_area",
// "employee_quantity",
// "enterprise_month_output",
// "position",
// "post_title",
// "month_income",
// "mate_name",
// "mate_mobile",
// "mate_id_no",
// "mate_education",
// "mate_company_name",
// "mate_company_address",
// "mate_company_contact_no",
// "gua_name",
// "gua_mobile",
// "gua_id_no",
// "gua_phone",
// "gua_company_name",
// "gua_company_address",
// "gua_house_asset_address",
// "emergency_name1",
// "emergency_relation1",
// "emergency_mobile1",
// "emergency_name2",
// "emergency_relation2",
// "emergency_mobile2",
// "jour_datetime_start",
// "jour_datetime_end",
// "jour_income",
// "jour_expend",
// "jour_balance",
// "jour_month_income",
// "jour_month_expend",
// "jour_remark",
// "house_contract",
// "house_picture",
// "is_advance_fund",
// "sale_user_id",
// "company_code",
// "apply_datetime",
// "cur_node_code"

// {"loanProductCode":"p001", "creditCode":"C201805301446505939681",
// "bizType":"1", "loanPeriod":"2020-01-01",
// "invoiceCompany":"开票单位", "carBrand":"品牌", "originalPrice":"50000",
// "invoicePrice":"45000",
// "carColor":"颜色", "monthDeposit":"2000", "firstAmount":"10000",
// "firstRate":"0.2",
// "loanAmount":"50000", "settleAddress":"落户地点", "applyUserName":"申请人姓名",
// "gender":"性别",
// "marryState":"婚姻状况", "nation":"民族", "education":"学历", "idNo":"11111111",
// "familyNumber":"4",
// "mobile":"17611591955", "nowAddress":"现居住地址", "postCode1":"043200",
// "residenceAddress":"户口所在地",
// "postCode2":"043200", "familyMainAsset":"家庭主要财产",
// "mainAssetInclude":"主要财产包括",
// "mainIncome":"主要收入来源", "workCompanyName":"工作单位名称",
// "workCompanyAddress":"工作单位地址",
// "selfCompanyArea":"自营公司单位面积", "employeeQuantity":"员工数量",
// "enterpriseMonthOutput":"企业月产值",
// "position":"职位", "postTitle":"职称", "monthIncome":"月收入", "mateName":"String",
// "mateMobile":"String", "mateIdNo":"String", "mateEducation":"String",
// "mateCompanyName":"String",
// "mateCompanyAddress":"String", "mateCompanyContactNo":"String",
// "guaName":"String",
// "guaMobile":"String", "guaIdNo":"String", "guaPhone":"String",
// "guaCompanyName":"String",
// "guaCompanyAddress":"String", "guaHouseAssetAddress":"String",
// "emergencyName1":"String",
// "emergencyRelation1":"String", "emergencyMobile1":"String",
// "emergencyName2":"String",
// "emergencyRelation2":"String", "emergencyMobile2":"String",
// "jourDatetimeStart":"String",
// "jourDatetimeEnd":"String", "jourIncome":"String", "jourExpend":"String",
// "jourBalance":"String",
// "jourMonthIncome":"String", "jourMonthExpend":"String",
// "jourRemark":"String",
// "houseContract":"String", "housePicture":"String", "isAdvanceFund":"String",
// "remark":"String"}
