/*
-- Query: SELECT `type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark` FROM tsys_node_flow
-- Date: 2018-06-16 16:09
*/
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('001','001_01','001_02',NULL,'担保合同,抵押合同',NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('001','001_02','001_03',NULL,'电饭锅',NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('001','001_03','001_09','001_04',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('001','001_04','001_02','',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_01','002_02',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_02','002_03','002_04',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_03','002_05','002_04',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_04','002_02','',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_05','002_06',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_06','002_07','002_08',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_07','002_09','',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_08','002_06',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_09','002_10','',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_10','002_11','002_12',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_12','002_10',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_11','002_13',NULL,'购车合同',NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_13','002_14',NULL,'合同',NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_14','002_15',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_15','002_16',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_16','002_17',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_17','002_18',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_18','002_19','','合同',NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_19','002_20','','合同,抵押合同',NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_20','002_21',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_21','002_22',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('002','002_22','002_23',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('003','003_02','003_03','003_01',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('003','003_03','003_04','003_02',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('003','003_04','003_05','003_02',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('003','003_05','003_06','003_02',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('003','003_06','003_07',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('003','003_08','003_09',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('003','003_09','003_10',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('003','003_10','003_11',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('003','003_11','003_17','003_13',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('003','003_17','003_18',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('003','003_18','003_19','003_20',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('003','003_19','003_22','003_21',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('004','004_01','004_02','004_03',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('004','004_06','004_07',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('005','005_02','005_03',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('006','006_01','006_02','006_03',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('006','006_03','006_04','006_05',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('007','007_01','007_02',NULL,NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('007','007_02','007_03','007_05',NULL,NULL);
INSERT INTO `tsys_node_flow` (`type`,`current_node`,`next_node`,`back_node`,`file_list`,`remark`) VALUES ('007','007_03','007_04','007_05',NULL,NULL);



/*
-- Query: SELECT * FROM dev_xn_wzcd.tsys_node
-- Date: 2018-06-16 16:10
*/
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('001_01','填写征信单','001',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('001_02','录入征信源结果','001',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('001_03','征信初审','001',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('001_04','征信一审','001',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('001_05','重新上传征信资料','001',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('002_01','填写预算单','002',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('002_02','区域总经理准入审核','002',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('002_03','省分公司总经理审核','002',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('002_04','准入审核二审','002',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('002_05','重新填写预算单','002',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('002_06','垫资审核','002',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('003_01','确认用款单','003',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('003_02','区域总经理审核','003',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('003_03','省分公司总经理审核','003',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('003_04','总公司制单','003',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('003_05','确认打款给车行','003',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('003_06','重新确认用款单','003',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('004_01','确认用款单','004',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('004_02','区域总经理审核','004',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('004_03','省分公司总经理审核','004',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('004_04','分公司制单','004',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('004_05','确认打款给分公司','004',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('004_06','确认打款给车行','004',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('004_07','重新确认用款单','004',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('007_01','确认提交银行','007',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('007_02','分公司内勤寄送银行材料','007',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('007_03','总公司内勤收件并核查','007',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('007_04','总公司内勤寄送银行材料','007',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('007_05','银行驻点收件并核查','007',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('007_06','确认收款','007',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('007_07','分公司内勤寄送银行材料待补件','007',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('007_08','总公司内勤寄送银行材料待补件','007',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('008_01','确认提交银行','008',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('008_02','分公司内勤寄送银行材料','008',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('008_03','总公司内勤收件并核查','008',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('008_04','总公司内勤寄送银行材料','008',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('008_05','银行驻点收件并核查','008',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('008_06','抵押完成','008',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('008_07','分公司内勤寄送银行材料待补件','008',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('008_08','总公司内勤寄送银行材料待补件','008',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('009_01','确认提交银行','009',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('009_02','总公司准备并寄送合同到分公司','009',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('009_03','分公司内勤收件并核查','009',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('009_04','分公司准备并寄送抵押材料','009',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('009_05','总公司内勤收件并核查','009',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('009_06','总公司寄送银行','009',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('009_07','银行驻点收件并核查','009',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('009_08','抵押完成','009',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('009_09','总公司寄送合同到分公司待补件','009',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('009_10','分公司寄送抵押材料待补件','009',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('009_11','总公司寄送到银行待补件','009',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('010_01','待入档','010',NULL);
INSERT INTO `tsys_node` (`code`,`name`,`type`,`remark`) VALUES ('010_02','已入档','010',NULL);
