INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('0',NULL,'collection_way','催收方式','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_way','telephone','电话','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_way','door','上门','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_way','takecar','拖车','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_way','judge','诉讼','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');

INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('0',NULL,'collection_process','催收过程','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_process','no_people_listen','无人接听','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_process','close_phone','关机','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_process','reject_listen','拒绝接听','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_process','no_people_home','无人在家','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_process','reject_meet','拒绝接见','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_process','mistake_address','住址有误','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_process','car_lose','汽车失联','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');

INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('0',NULL,'collection_wish','客户意愿','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_wish','promise_repay','承诺还款','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_wish','rejust_repay','拒绝还款','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_wish','part_repay','部分还款','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');

INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('0',NULL,'collection_result','催收结果','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_result','all_repay','全额还款','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_result','part_repay','部分还款','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_result','provide_deposit','提供押金','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_result','rejust_repay','拒绝还款','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_result','take_car','拖车处理','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_result','judge','诉讼','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','collection_result','replace_repay','代偿','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');

INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('0',NULL,'deal_result','催收方式','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','deal_result','1','已赎回','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','deal_result','2','出售','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','deal_result','3','偿还逾期金额并提供保证金','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','deal_result','4','司法诉讼','admin',now(),'','CD-CWZCD000020','CD-CWZCD000020');
